/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

import Excepciones.OBException;
import java.text.SimpleDateFormat;
import java.util.Date;
import Logica.Certificado;
import java.sql.SQLException;
import java.text.ParseException;
import java.time.DateTimeException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Liam
 */
public class Listar_Certificados_Pacientes extends javax.swing.JFrame {

    /**
     * Creates new form Listar_Certificados_Pacientes
     */
    public Listar_Certificados_Pacientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Fecha_1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Fecha_2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_datos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btn_Buscar = new javax.swing.JButton();
        btn_Borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CI");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setText("Fecha Inicio");

        jLabel3.setText("Fecha Fin");

        tabla_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Matricula", "CI", "Detalle", "Dias de Reposo", "Mutualista", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(tabla_datos);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("                               Listado de Certificaciones Pacientes");

        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        btn_Borrar.setText("Borrar");
        btn_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txt_Fecha_1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Fecha_2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(59, 59, 59))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Buscar)
                .addGap(128, 128, 128)
                .addComponent(btn_Borrar)
                .addGap(229, 229, 229))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Fecha_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Fecha_2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Buscar)
                    .addComponent(btn_Borrar))
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        Date fecha1=null;
        Date fecha2=null;
        Date comparacion=null;
        Date fechaActual=new Date();
        Integer cedula=null;
        Certificado certificado=null ; 
        DefaultTableModel modelo= new DefaultTableModel();
        modelo.setColumnIdentifiers(new Object[]{"Matricula","CI","Detalle","Dias de Reposo","Mutualista","Fecha"});
        try {
           SimpleDateFormat formato= new SimpleDateFormat("dd/MM/yyyy");
            fecha1=formato.parse(txt_Fecha_1.getText());
            fecha2=formato.parse(txt_Fecha_2.getText());
            cedula=Integer.parseInt(txt_cedula.getText());
            comparacion=formato.parse("01/01/1900");
            fechaActual.getTime();
           
           if(txt_cedula.getText()==null || txt_cedula.getText().isEmpty()|| Integer.parseInt(txt_cedula.getText())<=0){
               JOptionPane.showMessageDialog(null,"Debe ingresar la cedula");
             }
           else if(txt_Fecha_1.getText()==null || txt_Fecha_1.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null,"Debe ingresar La fecha de Inicio");
            }
           else if(txt_Fecha_2.getText()==null || txt_Fecha_2.getText().isEmpty()){
               JOptionPane.showMessageDialog(null,"Debe ingresar la fecha de Fin");
            }
           else if(fecha2.before(fecha1)){
               JOptionPane.showMessageDialog(null,"La fecha de 'FIN' debe ser mayor que la fecha de 'INICIO'");
           }
           else if(fecha1.before(comparacion)){
               JOptionPane.showMessageDialog(null, "La fecha ingresada debe ser mayor al año '1900'");
           }
           else if(fecha2.before(comparacion)){
               JOptionPane.showMessageDialog(null,"La fecha ingresada debe ser mayor al año '1900' ");
           }
           else if(fecha1.after(fechaActual)){
               JOptionPane.showMessageDialog(null,"Fecha ingresada supero a la fecha actual, verifique..");
           }
           else if(fecha2.after(fechaActual)){
            JOptionPane.showMessageDialog(null,"Fecha ingresada supero a la fecha actual, verifique..");
        }    
           
           else{
           
          
           certificado= Persistencia.PersistenciaCertificado.Listar_Certificados_Paciente(cedula,fecha1,fecha2);
           modelo.addRow(new Object[]{certificado.getMatricula(),certificado.getCI(),certificado.getDetalle(),certificado.getDiasReposo(),certificado.getMutualista(),certificado.getFecha()});
           tabla_datos.setModel(modelo); 
           }   
           
        }catch (ParseException e){
            JOptionPane.showMessageDialog(null,"Error en el formato de fecha ingresada");
        }catch(OBException | SQLException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,"Error al ingresar la cedula, solo caracteres numericos");
        }catch(NullPointerException e){
            
        }
           
        
        
        
        
        
        
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrarActionPerformed
        txt_Fecha_1.setText("");
        txt_Fecha_2.setText("");
        txt_cedula.setText("");
    }//GEN-LAST:event_btn_BorrarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_datos;
    private javax.swing.JTextField txt_Fecha_1;
    private javax.swing.JTextField txt_Fecha_2;
    private javax.swing.JTextField txt_cedula;
    // End of variables declaration//GEN-END:variables
}
