/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

/**
 *
 * @author Carlos
 */
public class Menu_mutualista extends javax.swing.JFrame {

    /**
     * Creates new form Menu_mutualista
     */
    public Menu_mutualista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_agregarMedico = new javax.swing.JButton();
        btn_modificarMedico = new javax.swing.JButton();
        btn_certificados = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu Mutualista");

        btn_agregarMedico.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_agregarMedico.setForeground(new java.awt.Color(0, 51, 255));
        btn_agregarMedico.setText("Agregar Medico");
        btn_agregarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarMedicoActionPerformed(evt);
            }
        });

        btn_modificarMedico.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_modificarMedico.setForeground(new java.awt.Color(0, 204, 51));
        btn_modificarMedico.setText("Modificar Medico");
        btn_modificarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarMedicoActionPerformed(evt);
            }
        });

        btn_certificados.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btn_certificados.setForeground(new java.awt.Color(0, 204, 204));
        btn_certificados.setText("Certificados");
        btn_certificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_certificadosActionPerformed(evt);
            }
        });

        btn_modificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_modificar.setForeground(new java.awt.Color(255, 51, 255));
        btn_modificar.setText("Modificar Mutualista");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_agregarMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_modificarMedico, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                    .addComponent(btn_certificados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btn_agregarMedico)
                .addGap(78, 78, 78)
                .addComponent(btn_modificarMedico)
                .addGap(77, 77, 77)
                .addComponent(btn_certificados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(btn_modificar)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarMedicoActionPerformed
        
        Registrar_Medico m= new Registrar_Medico();
        m.setVisible(true);
        
        
    }//GEN-LAST:event_btn_agregarMedicoActionPerformed

    private void btn_modificarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarMedicoActionPerformed
        Modificar_medico mod= new Modificar_medico();
        mod.setVisible(true);
    }//GEN-LAST:event_btn_modificarMedicoActionPerformed

    private void btn_certificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_certificadosActionPerformed
        Listar_Certificados_Medicos cer= new Listar_Certificados_Medicos();
        cer.setVisible(true);
    }//GEN-LAST:event_btn_certificadosActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
       Modificar_Datos_Mutualista mod= new Modificar_Datos_Mutualista();
       mod.setVisible(true);
    }//GEN-LAST:event_btn_modificarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarMedico;
    private javax.swing.JButton btn_certificados;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_modificarMedico;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
