/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaGUI;

/**
 *
 * @author Liam
 */
public class Menu_Usuarario extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Usuarario
     */
    public Menu_Usuarario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_modificar_datos = new javax.swing.JButton();
        btn_ver_certificados = new javax.swing.JButton();
        btn_pagoXbps = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu ");

        btn_modificar_datos.setBackground(new java.awt.Color(255, 255, 255));
        btn_modificar_datos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_modificar_datos.setForeground(new java.awt.Color(0, 204, 204));
        btn_modificar_datos.setText("Modificar Datos");
        btn_modificar_datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificar_datosActionPerformed(evt);
            }
        });

        btn_ver_certificados.setBackground(new java.awt.Color(255, 255, 255));
        btn_ver_certificados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_ver_certificados.setForeground(new java.awt.Color(0, 204, 0));
        btn_ver_certificados.setText("Certificados");
        btn_ver_certificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ver_certificadosActionPerformed(evt);
            }
        });

        btn_pagoXbps.setBackground(new java.awt.Color(255, 255, 255));
        btn_pagoXbps.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_pagoXbps.setForeground(new java.awt.Color(0, 0, 255));
        btn_pagoXbps.setText("Calcular Pago por BPS");
        btn_pagoXbps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagoXbpsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_modificar_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ver_certificados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_pagoXbps, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btn_modificar_datos)
                .addGap(43, 43, 43)
                .addComponent(btn_ver_certificados)
                .addGap(42, 42, 42)
                .addComponent(btn_pagoXbps)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificar_datosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificar_datosActionPerformed
        Modificar_Paciente paciente= new Modificar_Paciente();
        paciente.setVisible(true);
        
    }//GEN-LAST:event_btn_modificar_datosActionPerformed

    private void btn_ver_certificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ver_certificadosActionPerformed
       Listar_Certificados_Pacientes certificados= new Listar_Certificados_Pacientes();
        certificados.setVisible(true);
    }//GEN-LAST:event_btn_ver_certificadosActionPerformed

    private void btn_pagoXbpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagoXbpsActionPerformed
        Pago_de_Bps bps=new Pago_de_Bps();
        bps.setVisible(true);
    }//GEN-LAST:event_btn_pagoXbpsActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_modificar_datos;
    private javax.swing.JButton btn_pagoXbps;
    private javax.swing.JButton btn_ver_certificados;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
